### ISSUE TITLE
Color function not recognized

### ISSUE THREAD

**Issue by shuffler10** [Damnae/storybrew#10]
Just tried to use some simple coloring (using RGB) (recreating Okaerinasai) when I got to this problem
When trying to do the sprite that overlaps the spectums,I found that the color only goes once, then stays white in the Storybrew program. But when exported, the first color is black, then all rest are white.

Here is the code for the CS
`
            //Layers Init
            var BackgroundLayer = GetLayer("Background Layer");
            var SpectrumLayer = GetLayer("Spectrum Layer");
            var SpectrumTopLayer = GetLayer("Spectrum Layer Top");
            var LyricsLayer = GetLayer("Lyrics Layer");
            //Objects Init
            var SpectrumTop = SpectrumTopLayer.CreateSprite("sb/pixel-2.png", OsbOrigin.Centre, new Vector2(320,240));
            SpectrumTop.Color(OsbEasing.None, 259675, 259718, 0, 0, 0, 12, 38, 52);
            SpectrumTop.ScaleVec(OsbEasing.None, 259675, 286948, 426.875, 21.875, 426.875, 21.875);
            SpectrumTop.Fade(OsbEasing.None, 275996, 276039, 1, 0);
            SpectrumTop.Color(OsbEasing.None, 259718, 259761, 12, 38, 52, 22, 71, 98);
            SpectrumTop.Color(OsbEasing.None, 259761, 259803, 22, 71, 98, 31, 99, 136);
            SpectrumTop.Color(OsbEasing.None, 259803, 259846, 31, 99, 136, 39, 123, 168);
            SpectrumTop.Color(OsbEasing.None, 259846, 259888, 39, 123, 168, 44, 140, 192);
            SpectrumTop.Color(OsbEasing.None, 259888, 259931, 44, 140, 192, 48, 153, 210);
            SpectrumTop.Color(OsbEasing.None, 259931, 259974, 48, 153, 210, 51, 161, 220);
            for (int i = 259974; i < 267261; i += 22)
            {
                int lateI = i + 22; 
                if(i % 2 == 0)
                {
                SpectrumTop.Color(OsbEasing.None, i, lateI, 51, 161, 220, 52, 164, 224);
                }else{
                SpectrumTop.Color(OsbEasing.None, i, lateI, 52, 164, 224, 52, 164, 224);    
                }
            }`
And the exported OSB
`[Events]
//Background and Video events
//Storyboard Layer 0 (Background)
//Storyboard Layer 1 (Fail)
//Storyboard Layer 2 (Pass)
//Storyboard Layer 3 (Foreground)
Sprite,Foreground,Centre,"sb/pixel-2.png",320,240
 C,0,259675,259718,0,0,0,255,255,255
 V,0,259675,286948,426.875,21.875
 F,0,275996,276039,1,0
 C,0,259718,259761,255,255,255
 C,0,259761,259803,255,255,255
 C,0,259803,259846,255,255,255
 C,0,259846,259888,255,255,255
 C,0,259888,259931,255,255,255
 C,0,259931,259974,255,255,255
 C,0,259974,259996,255,255,255
 C,0,259996,260018,255,255,255
 C,0,260018,260040,255,255,255
 C,0,260040,260062,255,255,255
 C,0,260062,260084,255,255,255
 C,0,260084,260106,255,255,255
 C,0,260106,260128,255,255,255
 C,0,260128,260150,255,255,255
 C,0,260150,260172,255,255,255
 C,0,260172,260194,255,255,255
 C,0,260194,260216,255,255,255
 C,0,260216,260238,255,255,255
 C,0,260238,260260,255,255,255
 C,0,260260,260282,255,255,255
 C,0,260282,260304,255,255,255
 C,0,260304,260326,255,255,255
 C,0,260326,260348,255,255,255
 C,0,260348,260370,255,255,255
 C,0,260370,260392,255,255,255
 C,0,260392,260414,255,255,255
 C,0,260414,260436,255,255,255
 C,0,260436,260458,255,255,255
 C,0,260458,260480,255,255,255
 C,0,260480,260502,255,255,255
 C,0,260502,260524,255,255,255
 C,0,260524,260546,255,255,255
 C,0,260546,260568,255,255,255
 C,0,260568,260590,255,255,255
 C,0,260590,260612,255,255,255
 C,0,260612,260634,255,255,255
 C,0,260634,260656,255,255,255
 C,0,260656,260678,255,255,255
 C,0,260678,260700,255,255,255
 C,0,260700,260722,255,255,255
 C,0,260722,260744,255,255,255
 C,0,260744,260766,255,255,255
 C,0,260766,260788,255,255,255
 C,0,260788,260810,255,255,255
 C,0,260810,260832,255,255,255
 C,0,260832,260854,255,255,255
 C,0,260854,260876,255,255,255
 C,0,260876,260898,255,255,255
 C,0,260898,260920,255,255,255
 C,0,260920,260942,255,255,255
 C,0,260942,260964,255,255,255
 C,0,260964,260986,255,255,255
 C,0,260986,261008,255,255,255
 C,0,261008,261030,255,255,255
 C,0,261030,261052,255,255,255
 C,0,261052,261074,255,255,255
 C,0,261074,261096,255,255,255
 C,0,261096,261118,255,255,255
 C,0,261118,261140,255,255,255
 C,0,261140,261162,255,255,255
 C,0,261162,261184,255,255,255
 C,0,261184,261206,255,255,255
 C,0,261206,261228,255,255,255
 C,0,261228,261250,255,255,255
 C,0,261250,261272,255,255,255
 C,0,261272,261294,255,255,255
 C,0,261294,261316,255,255,255
 C,0,261316,261338,255,255,255
 C,0,261338,261360,255,255,255
 C,0,261360,261382,255,255,255
 C,0,261382,261404,255,255,255
 C,0,261404,261426,255,255,255
 C,0,261426,261448,255,255,255
 C,0,261448,261470,255,255,255
 C,0,261470,261492,255,255,255
 C,0,261492,261514,255,255,255
 C,0,261514,261536,255,255,255
 C,0,261536,261558,255,255,255
 C,0,261558,261580,255,255,255
 C,0,261580,261602,255,255,255
 C,0,261602,261624,255,255,255
 C,0,261624,261646,255,255,255
 C,0,261646,261668,255,255,255
 C,0,261668,261690,255,255,255
 C,0,261690,261712,255,255,255
 C,0,261712,261734,255,255,255
 C,0,261734,261756,255,255,255
 C,0,261756,261778,255,255,255
 C,0,261778,261800,255,255,255
 C,0,261800,261822,255,255,255
 C,0,261822,261844,255,255,255
 C,0,261844,261866,255,255,255
 C,0,261866,261888,255,255,255
 C,0,261888,261910,255,255,255
 C,0,261910,261932,255,255,255
 C,0,261932,261954,255,255,255
 C,0,261954,261976,255,255,255
 C,0,261976,261998,255,255,255
 C,0,261998,262020,255,255,255
 C,0,262020,262042,255,255,255
 C,0,262042,262064,255,255,255
 C,0,262064,262086,255,255,255
 C,0,262086,262108,255,255,255
 C,0,262108,262130,255,255,255
 C,0,262130,262152,255,255,255
 C,0,262152,262174,255,255,255
 C,0,262174,262196,255,255,255
 C,0,262196,262218,255,255,255
 C,0,262218,262240,255,255,255
 C,0,262240,262262,255,255,255
 C,0,262262,262284,255,255,255
 C,0,262284,262306,255,255,255
 C,0,262306,262328,255,255,255
 C,0,262328,262350,255,255,255
 C,0,262350,262372,255,255,255
 C,0,262372,262394,255,255,255
 C,0,262394,262416,255,255,255
 C,0,262416,262438,255,255,255
 C,0,262438,262460,255,255,255
 C,0,262460,262482,255,255,255
 C,0,262482,262504,255,255,255
 C,0,262504,262526,255,255,255
 C,0,262526,262548,255,255,255
 C,0,262548,262570,255,255,255
 C,0,262570,262592,255,255,255
 C,0,262592,262614,255,255,255
 C,0,262614,262636,255,255,255
 C,0,262636,262658,255,255,255
 C,0,262658,262680,255,255,255
 C,0,262680,262702,255,255,255
 C,0,262702,262724,255,255,255
 C,0,262724,262746,255,255,255
 C,0,262746,262768,255,255,255
 C,0,262768,262790,255,255,255
 C,0,262790,262812,255,255,255
 C,0,262812,262834,255,255,255
 C,0,262834,262856,255,255,255
 C,0,262856,262878,255,255,255
 C,0,262878,262900,255,255,255
 C,0,262900,262922,255,255,255
 C,0,262922,262944,255,255,255
 C,0,262944,262966,255,255,255
 C,0,262966,262988,255,255,255
 C,0,262988,263010,255,255,255
 C,0,263010,263032,255,255,255
 C,0,263032,263054,255,255,255
 C,0,263054,263076,255,255,255
 C,0,263076,263098,255,255,255
 C,0,263098,263120,255,255,255
 C,0,263120,263142,255,255,255
 C,0,263142,263164,255,255,255
 C,0,263164,263186,255,255,255
 C,0,263186,263208,255,255,255
 C,0,263208,263230,255,255,255
 C,0,263230,263252,255,255,255
 C,0,263252,263274,255,255,255
 C,0,263274,263296,255,255,255
 C,0,263296,263318,255,255,255
 C,0,263318,263340,255,255,255
 C,0,263340,263362,255,255,255
 C,0,263362,263384,255,255,255
 C,0,263384,263406,255,255,255
 C,0,263406,263428,255,255,255
 C,0,263428,263450,255,255,255
 C,0,263450,263472,255,255,255
 C,0,263472,263494,255,255,255
 C,0,263494,263516,255,255,255
 C,0,263516,263538,255,255,255
 C,0,263538,263560,255,255,255
 C,0,263560,263582,255,255,255
 C,0,263582,263604,255,255,255
 C,0,263604,263626,255,255,255
 C,0,263626,263648,255,255,255
 C,0,263648,263670,255,255,255
 C,0,263670,263692,255,255,255
 C,0,263692,263714,255,255,255
 C,0,263714,263736,255,255,255
 C,0,263736,263758,255,255,255
 C,0,263758,263780,255,255,255
 C,0,263780,263802,255,255,255
 C,0,263802,263824,255,255,255
 C,0,263824,263846,255,255,255
 C,0,263846,263868,255,255,255
 C,0,263868,263890,255,255,255
 C,0,263890,263912,255,255,255
 C,0,263912,263934,255,255,255
 C,0,263934,263956,255,255,255
 C,0,263956,263978,255,255,255
 C,0,263978,264000,255,255,255
 C,0,264000,264022,255,255,255
 C,0,264022,264044,255,255,255
 C,0,264044,264066,255,255,255
 C,0,264066,264088,255,255,255
 C,0,264088,264110,255,255,255
 C,0,264110,264132,255,255,255
 C,0,264132,264154,255,255,255
 C,0,264154,264176,255,255,255
 C,0,264176,264198,255,255,255
 C,0,264198,264220,255,255,255
 C,0,264220,264242,255,255,255
 C,0,264242,264264,255,255,255
 C,0,264264,264286,255,255,255
 C,0,264286,264308,255,255,255
 C,0,264308,264330,255,255,255
 C,0,264330,264352,255,255,255
 C,0,264352,264374,255,255,255
 C,0,264374,264396,255,255,255
 C,0,264396,264418,255,255,255
 C,0,264418,264440,255,255,255
 C,0,264440,264462,255,255,255
 C,0,264462,264484,255,255,255
 C,0,264484,264506,255,255,255
 C,0,264506,264528,255,255,255
 C,0,264528,264550,255,255,255
 C,0,264550,264572,255,255,255
 C,0,264572,264594,255,255,255
 C,0,264594,264616,255,255,255
 C,0,264616,264638,255,255,255
 C,0,264638,264660,255,255,255
 C,0,264660,264682,255,255,255
 C,0,264682,264704,255,255,255
 C,0,264704,264726,255,255,255
 C,0,264726,264748,255,255,255
 C,0,264748,264770,255,255,255
 C,0,264770,264792,255,255,255
 C,0,264792,264814,255,255,255
 C,0,264814,264836,255,255,255
 C,0,264836,264858,255,255,255
 C,0,264858,264880,255,255,255
 C,0,264880,264902,255,255,255
 C,0,264902,264924,255,255,255
 C,0,264924,264946,255,255,255
 C,0,264946,264968,255,255,255
 C,0,264968,264990,255,255,255
 C,0,264990,265012,255,255,255
 C,0,265012,265034,255,255,255
 C,0,265034,265056,255,255,255
 C,0,265056,265078,255,255,255
 C,0,265078,265100,255,255,255
 C,0,265100,265122,255,255,255
 C,0,265122,265144,255,255,255
 C,0,265144,265166,255,255,255
 C,0,265166,265188,255,255,255
 C,0,265188,265210,255,255,255
 C,0,265210,265232,255,255,255
 C,0,265232,265254,255,255,255
 C,0,265254,265276,255,255,255
 C,0,265276,265298,255,255,255
 C,0,265298,265320,255,255,255
 C,0,265320,265342,255,255,255
 C,0,265342,265364,255,255,255
 C,0,265364,265386,255,255,255
 C,0,265386,265408,255,255,255
 C,0,265408,265430,255,255,255
 C,0,265430,265452,255,255,255
 C,0,265452,265474,255,255,255
 C,0,265474,265496,255,255,255
 C,0,265496,265518,255,255,255
 C,0,265518,265540,255,255,255
 C,0,265540,265562,255,255,255
 C,0,265562,265584,255,255,255
 C,0,265584,265606,255,255,255
 C,0,265606,265628,255,255,255
 C,0,265628,265650,255,255,255
 C,0,265650,265672,255,255,255
 C,0,265672,265694,255,255,255
 C,0,265694,265716,255,255,255
 C,0,265716,265738,255,255,255
 C,0,265738,265760,255,255,255
 C,0,265760,265782,255,255,255
 C,0,265782,265804,255,255,255
 C,0,265804,265826,255,255,255
 C,0,265826,265848,255,255,255
 C,0,265848,265870,255,255,255
 C,0,265870,265892,255,255,255
 C,0,265892,265914,255,255,255
 C,0,265914,265936,255,255,255
 C,0,265936,265958,255,255,255
 C,0,265958,265980,255,255,255
 C,0,265980,266002,255,255,255
 C,0,266002,266024,255,255,255
 C,0,266024,266046,255,255,255
 C,0,266046,266068,255,255,255
 C,0,266068,266090,255,255,255
 C,0,266090,266112,255,255,255
 C,0,266112,266134,255,255,255
 C,0,266134,266156,255,255,255
 C,0,266156,266178,255,255,255
 C,0,266178,266200,255,255,255
 C,0,266200,266222,255,255,255
 C,0,266222,266244,255,255,255
 C,0,266244,266266,255,255,255
 C,0,266266,266288,255,255,255
 C,0,266288,266310,255,255,255
 C,0,266310,266332,255,255,255
 C,0,266332,266354,255,255,255
 C,0,266354,266376,255,255,255
 C,0,266376,266398,255,255,255
 C,0,266398,266420,255,255,255
 C,0,266420,266442,255,255,255
 C,0,266442,266464,255,255,255
 C,0,266464,266486,255,255,255
 C,0,266486,266508,255,255,255
 C,0,266508,266530,255,255,255
 C,0,266530,266552,255,255,255
 C,0,266552,266574,255,255,255
 C,0,266574,266596,255,255,255
 C,0,266596,266618,255,255,255
 C,0,266618,266640,255,255,255
 C,0,266640,266662,255,255,255
 C,0,266662,266684,255,255,255
 C,0,266684,266706,255,255,255
 C,0,266706,266728,255,255,255
 C,0,266728,266750,255,255,255
 C,0,266750,266772,255,255,255
 C,0,266772,266794,255,255,255
 C,0,266794,266816,255,255,255
 C,0,266816,266838,255,255,255
 C,0,266838,266860,255,255,255
 C,0,266860,266882,255,255,255
 C,0,266882,266904,255,255,255
 C,0,266904,266926,255,255,255
 C,0,266926,266948,255,255,255
 C,0,266948,266970,255,255,255
 C,0,266970,266992,255,255,255
 C,0,266992,267014,255,255,255
 C,0,267014,267036,255,255,255
 C,0,267036,267058,255,255,255
 C,0,267058,267080,255,255,255
 C,0,267080,267102,255,255,255
 C,0,267102,267124,255,255,255
 C,0,267124,267146,255,255,255
 C,0,267146,267168,255,255,255
 C,0,267168,267190,255,255,255
 C,0,267190,267212,255,255,255
 C,0,267212,267234,255,255,255
 C,0,267234,267256,255,255,255
 C,0,267256,267278,255,255,255
//Storyboard Sound Samples
`

**Comment by shuffler10** [comment]
Sorry if it is too big, too lazy to upload the files

**Comment by Damnae** [comment]
RGB color commands use values from 0 to 1 rather than 0 to 255.
https://github.com/Damnae/storybrew/wiki/Sprite-Methods#color
