### ISSUE TITLE
Unable to configure all but the first effect based on the same script

### ISSUE THREAD

**Issue by TicClickie** [Damnae/storybrew#12]
Steps to reproduce:
* Create a script with a [Configurable] field;
* Add a new effect which utilizes the same script (as a result, you'll get two of them on the side panel);
* Notice you can't change the freshly added effect's fields, not even a random seed one: https://tc.s-ul.eu/UoGWAxr9.gif

**Comment by TicClickie** [comment]
it also shows a blank configuration tab on the left when you remove the effect and re-add it; takes a file edit to make project recognize script's configurable fields.

**Comment by Damnae** [comment]
Should be fixed in 1.20

**Comment by TicClickie** [comment]
(yeah, it's fixed now)
