### ISSUE TITLE
CodeDomProvider is not supporting C# 6 features

### ISSUE THREAD

**Issue by Darky1** [Damnae/storybrew#28]
Scripts like this:
```csharp
String txt = "text";
Log($"This is {txt}");
```
Doesn't compile because of missing C# 6 features.
https://github.com/Damnae/storybrew/blob/master/editor/Scripting/ScriptCompiler.cs#L51

**Comment by Damnae** [comment]
I'm aware, feel free to improve it /:D/

**Comment by Damnae** [comment]
Holy shit you did it.
