### ISSUE TITLE
[Small Issue] Grammatical error in error message

### ISSUE THREAD

**Issue by Vertiquo** [Damnae/storybrew#30]
https://github.com/Damnae/storybrew/blob/30dab2c9f1cb9ff89ed3a1bd3d8580e0675efb12/editor/editor.csproj#L212

> <ErrorText>This Project has references to one or more NuGet-Packages that are missing on this Computer. Use the recovery of NuGet-Packages to download the missing files. For more **informations**, visit "http://go.microsoft.com/fwlink/?LinkID=322105. The file is {0}."</ErrorText>

It should be "information", not "informations", as "information" is a mass-noun which does not possess a plural.

~~I know this might not be worth opening an issue, so sorry in advance.~~

~~Also computer should not start capitalized.~~

**Comment by Damnae** [comment]
blame miscrosoft. not Me,
