### ISSUE TITLE
Program updater request error.

### ISSUE THREAD

**Issue by MikiraSora** [Damnae/storybrew#42]
![image](https://user-images.githubusercontent.com/7549173/36643757-1e98a320-1a8b-11e8-87ba-265d52622071.png)

Github is force use TLS1.2 now and not support TLS1.0.
.Net framework 4.5 and latest is support TLS1.2 but default TLS1.0,please check. :D

**Comment by Damnae** [comment]
This is already fixed, but you will have to update manually this time:
https://github.com/Damnae/storybrew/releases/latest
