### ISSUE TITLE
HitObjectOverlay works only on one instance

### ISSUE THREAD

**Issue by NomegaGaming** [Damnae/storybrew#50]
https://i.imgur.com/jlj37Qk.png

 I set up the hitobject overlay once in the first kiai of the map, and it works fine, it's all set up properly, however when using it in the second kiai it only works for 8 bars before giving me an execution error. I tried fixing this with another instance but it doesn't work either. Is the timestamp used broken?

**Comment by Damnae** [comment]
This error means that the position of one of the hitobjects that you are trying to highlight is broken.

**Comment by NomegaGaming** [comment]
i moved the object that it broke on and it still isn't fixed.
