### ISSUE TITLE
Just asking whats the requirements!?

### ISSUE THREAD

**Issue by Rayanial** [Damnae/storybrew#52]
Im afraid that i cant run it since i have a bad pc but i can give you my specs.
Specs: 
Cpu: I3 2120
Gpu: Intel HD Graphics
Ram: 8gb
OS: Windows 10 32-bit (And yes i cant upgrade to 64 because it wont work)
Can i do some small things on it?
Also have a good day! :3

**Comment by Damnae** [comment]
Updating drivers can help, but in most cases sbrew needs a dedicated gpu to run. 
32 bit shouldn't be a problem.
