### ISSUE TITLE
Storybrew Really Hangy when lyrics effect used

### ISSUE THREAD

**Issue by dumb-stuff** [Damnae/storybrew#59]
![image](https://user-images.githubusercontent.com/59832159/132155090-9294c88b-5d31-4fa8-a384-e51520fe66ff.png)
This is what happen after I added lyric effect<br>
It always hang when when I add lyric effect.<br>
help

**Comment by Damnae** [comment]
Make you're using the last version, then replace the .exe with this one. [StorybrewEditor.zip](https://github.com/Damnae/storybrew/files/7114793/StorybrewEditor.zip)

Let the editor freeze until logs/freeze.log is created and send it here.

**Comment by dumb-stuff** [comment]
It is not hangy now. Thanks
