### ISSUE TITLE
Cryptic error message if GetMapsetBitmap is used for non-existing file in a subfolder

### ISSUE THREAD

**Issue by Endaris** [Damnae/storybrew#63]
Repro code:
`public override void Generate()
{
var bitmap = GetMapsetBitmap("sb/f/hello world.png");   
}`

This assumes that the folders `sb` and `sb/f` both exist in the mapset folder.

Resulting error message:
![grafik](https://user-images.githubusercontent.com/22120694/154841651-8f3319ea-bf7a-4c5a-a2aa-cf6e47ac327d.png)

Apparently something goes awry as it tries to do the fallback in GetMapsetBitmap and starts looking in the project folder but somehow gets lost there.

This only seems to occur when at least 2 folders are specified before the non-existing file, if I try the same with "sb/hello world.png" it correctly gives me a FileNotFoundException in Mapsetfolder/sb.

**Comment by Damnae** [comment]
Is that on latest version? I thought I fixed something like that already.

**Comment by Endaris** [comment]
Reproduced on 1.80.7909.25927 which I believe should be the latest version.
