### ISSUE TITLE
Editor Crashes on Startup when Windows has no enabled Audio Output devices

### ISSUE THREAD

**Issue by hongaaronc** [Damnae/storybrew#68]
Probably a niche case, but this was happening to me and it took me a while to figure out what was going on, so I figured I might as well file an issue for it.

Feel free to deprioritize or close this issue if you think it's too niche to be worth pursuing.

**Observations:**
I have a PC setup with only a DAC/AMP combo as my only audio output. The DAC/AMP uses its own external power supply, and I pretty much only turn it on when I plan to listen to something. When the DAC/AMP is off, it doesn't appear as a connected device in Windows.

I was opening my project in Storybrew and forgot to turn on my DAC/AMP. Basically this resulted in crashing on startup - and I realized the same thing applies for opening other projects, or creating a new one. Dived through the logs a bit, and figured out it was something related to initialization of the audio streams, and that made me finally remember to turn on my audio. After flipping the DAC/AMP on, I was able to finally open the editor.

Also worth noting that it's possible to start the editor with the DAC/AMP enabled successfully, then if I turn off the DAC/AMP, the editor doesn't crash (as expected). Turning it back on, also does not result in a crash, but preview audio can't be heard after doing so.

**Points of Interest:**
Probably need to gate out this method call:
https://github.com/Damnae/storybrew/blob/master/editor/ScreenLayers/ProjectMenu.cs#L77

Just not sure what the determination logic would look like for seeing if there's any connected audio devices.

I think the situation of adding an audio device mid-session after launching the editor, and having that trigger this method call is probably not worth the effort pursuing. However, just handling the initial editor launch gracefully (just preventing the crash, but not being able to play audio would be fine) might be worthwhile to prevent confusion.

**Comment by Damnae** [comment]
Should load with no audio now.

**Comment by hongaaronc** [comment]
Great! I'll try and verify the fix tonight.

**Comment by hongaaronc** [comment]
Oh I see, the fix is pending next release. I haven't built the project before so maybe I'll try doing that this weekend or so.

**Comment by hongaaronc** [comment]
Sorry this took a while, but finally got tried this out on v1.87. Looks like an error still occurs in this scenario, which prevents startup, but seems like you've updated the error message to be nice and descriptive - so I think from a user perspective it's pretty obvious how to fix this now.

![image](https://user-images.githubusercontent.com/5133530/209512037-df259802-d01a-406d-a67a-d778a8122b08.png)

Imo this is ok - now it's perfectly easy to figure out what to do from the user perspective. So this issue should be good to close out if you also think so.
