### ISSUE TITLE
Completed Wiki

### ISSUE THREAD

**Issue by Zerss** [Damnae/storybrew#7]
Hey,

First, thank you for making such an amazing tool. I'm just posting this because I think the Wiki needs more informations; I've been struggling with some issues about storyboarding such as Easings and element declarations (OsbSprite? StoryboardLayer?).

**Comment by Damnae** [comment]
If you're using vscode, it should show you available values as you type them:
![](http://puu.sh/oesq7/62eba83def.png)

If you need information that you can't find in the wiki, you can contact me in game and I'll help you, then add to the wiki if necessary.
