### ISSUE TITLE
Can add custom widget on the EffectConfigUi?

### ISSUE THREAD

**Issue by wanjiaXG** [Damnae/storybrew#71]
Like this usage scenario.
https://osu.wanjiaxg.com/cloud/usecurrenttime-demo.mp4

**Comment by wanjiaXG** [comment]
Configure custom control functions by StoryboardObjectGenerator.

**Comment by Damnae** [comment]
> It can be applied to use current time or select image file or more scenario.

These should not be in effect configuration. Picking the current time is already something you can do in the editor, just Ctrl-C anywhere like in osu!.

Implementation also has problems, like using global variables or letting the configuration fields call any method of any dll.

**Comment by wanjiaXG** [comment]
> > It can be applied to use current time or select image file or more scenario.
> 
> These should not be in effect configuration. Picking the current time is already something you can do in the editor, just Ctrl-C anywhere like in osu!.
> 
> Implementation also has problems, like using global variables or letting the configuration fields call any method of any dll.

yeah，it is bad code.
Now I want to see if you are interested in doing this function.
This time, I am just simulate it.
I just want to use storybrew more conveniently.
