### ISSUE TITLE
Storybrew gives an error on startup

### ISSUE THREAD

**Issue by gi-b716** [Damnae/storybrew#76]
When I open Storybrew using Windows 11 and try to create a new or open project, the following error pops up:
![image](https://github.com/Damnae/storybrew/assets/78394473/2345d07a-9e1b-46f6-8129-982c90bc8258)

Chinese translation of the second/third line:
- Length cannot be less than 0.
- Parameter name: length(ArgumentOutOfRangeException)

**Comment by Damnae** [comment]
Can you send logs/crash.log?

**Comment by gi-b716** [comment]
> Can you send logs/crash.log?
[crash.log](https://github.com/Damnae/storybrew/files/15051355/crash.log)

**Comment by gi-b716** [comment]
> > Can you send logs/crash.log?
> 
> [crash.log](https://github.com/Damnae/storybrew/files/15051355/crash.log)

It's in Chinese, so I'll translate it briefly
参数名 -> parameter name
位置 -> location/postion (I'm Chinese so I'm not sure which one:( )
行号 -> line number
在 -> exist

**Comment by gi-b716** [comment]
I've analyzed it myself and it's a problem when getting the Osu path.

**Comment by Damnae** [comment]
Yes, the registry entry seems missing or gives an undocumented exception when trying to read it. Working on a fix.

**Comment by gi-b716** [comment]
> Yes, the registry entry seems missing or gives an undocumented exception when trying to read it. Working on a fix.

thx！
