### ISSUE TITLE
Show looped sprites

### ISSUE THREAD

**Issue by Zerss** [Damnae/storybrew#8]
The editor does not show looped actions

**Comment by Damnae** [comment]
Are you talking about [loops](https://github.com/Damnae/storybrew/wiki/Sprite-Methods#loops)? They work for me, can you provide code where they don't?

**Comment by Zerss** [comment]
Well, it might be my computer/drivers, since loops aren't working at all. I'm just doing a simple StartTriggerGroup command (with an EndGroup command). But if I export to .osb, it's working fine.
So if that's just my computer (or my drivers), I guess it's still ok (if I can face the problem).
